version: '3.8'

services:
  db:
    image: postgres:16
    container_name: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    ports:
      - '5432:5432'
